// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $conversation from "./routes/conversation.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $private from "./routes/private.tsx";
import * as $sample from "./routes/sample.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $MSNForm from "./islands/MSNForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/conversation.tsx": $conversation,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/private.tsx": $private,
    "./routes/sample.tsx": $sample,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/MSNForm.tsx": $MSNForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
